In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly_express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from plotly.offline import init_notebook_mode
import requests
from bs4 import BeautifulSoup
import time
from tqdm import tqdm_notebook

In [8]:
x =np.arange(1,5)
a = len(x)
matr = x.reshape(-1,1) ** np.arange(a)
np.tril(matr.T)

array([[ 1,  0,  0,  0],
       [ 1,  2,  0,  0],
       [ 1,  4,  9,  0],
       [ 1,  8, 27, 64]], dtype=int32)

In [91]:
A = np.tril(([5]*4) ** np.arange(5).reshape(-1,1), -1)

In [54]:
B = np.tril(([4]*4) * np.arange(5).reshape(-1,1), -1).T

In [74]:
C = np.zeros(5)

In [80]:
c1=C.reshape(-1,1)

In [102]:
c2 = C.reshape(1,-1)

In [104]:
d = np.concatenate((A, c1), axis=1)

In [105]:
e = np.concatenate((B, c2), axis=0)

In [108]:
d+e+np.eye(5)

array([[  1.,   4.,   8.,  12.,  16.],
       [  5.,   1.,   8.,  12.,  16.],
       [ 25.,  25.,   1.,  12.,  16.],
       [125., 125., 125.,   1.,  16.],
       [625., 625., 625., 625.,   1.]])

In [114]:
A = np.tril(([1]*4) ** np.arange(5).reshape(-1,1), -1)
B = np.tril(([2]*4) * np.arange(5).reshape(-1,1), -1).T
C = np.zeros(5)
c1=C.reshape(-1,1)
c2 = C.reshape(1,-1)
d = np.concatenate((A, c1), axis=1)
e = np.concatenate((B, c2), axis=0)
s = d+e+np.eye(5)
round(np.linalg.det(s))

105.0

In [119]:
n = int(input())
m = int(input())
chisla = np.array(input().split(' '))
chisla = np.array(chisla, int)
chisla

2
3
1 2 3 4 5 6


array([1, 2, 3, 4, 5, 6])

In [175]:
data = pd.read_csv('test_data.csv', sep='\t')
d1 = data[data['in_hse_memes_group']]
d2 = data[data['in_hse_memes_group'] != 1]

a = d1[d1['male_dummy']==1]['wall_repost_cnt'].mean() > d2[d2['male_dummy']==0]['wall_repost_cnt'].mean() #1

b = data[data['city'] != 'Москва']['wall_like_mean'].mean() < 80 #2

d3 = data['political_cat'].dropna()
count = d3.value_counts().loc['либертарианские']
c = count / len(d3) >= 0.5 #3

d = data[data['country'] =='Узбекистан']['subscriptions_cnt'].mean() > data[data['country'] =='Россия']['subscriptions_cnt'].mean()
print(a,b,c,d, sep='\n')

True
True
False
True


In [183]:
n = int(input())
m = int(input())
chisla = np.array(input().split('\n'))
chisla = np.array(chisla, int)
k = chisla.reshape((n, m))
d = np.diag(k)
g = d[d != 0]
if g:
    print(np.prod(g))
else:
    print(-1)

2
3
1 2


ValueError: invalid literal for int() with base 10: '1 2'

In [196]:
n, m = map(int, input().split())
matrix = []
for i in range(n):
    row = list(map(int, input().split()))
    matrix.append(row)
m = np.diag(matrix)
c = np.count_nonzero(m)
if c == 0:
    print(-1)
else:
    matr = m[m!=0]
    print(np.prod(matr))

4 3
1 0 1
2 0 2
3 0 3
4 4 4
3


In [273]:
sorev = np.random.exponential(scale = 5, size=(100000,5))

In [289]:
X = np.min(sorev, axis=1)
Y = np.max(sorev, axis=1)
Z = Y - X
p1 = Z>5
round(p1.mean(), 3)

0.841

In [275]:
sorev1 = sorev[sorev[:, 0] >3]
X1 = np.min(sorev1, axis=1)
Y1 = np.max(sorev1, axis=1)
Z1 = Y1 - X1
p2 = Z1>5
p2.mean()

0.8840648593312981

In [286]:
sorev1 = sorev[sorev[:, 0] >3]
X1 = np.min(sorev1, axis=1)
Y1 = np.max(sorev1, axis=1)
Z1 = Y1 - X1
p2 = Z1>5
round(p2.mean())

1.0

In [284]:
sorev = np.random.exponential(scale = 5, size=(1000000,5))
X1 = np.min(sorev, axis=1)
Y1 = np.max(sorev, axis=1)
T = Y1[Y1 < 10]
Z = Y-X
(Z/len(T)).mean()

2.1604150126884907e-05

In [301]:
res = np.concatenate((X, Y[Y < 10]))
res

array([1.81011575, 2.33347028, 2.2240798 , ..., 8.19944775, 8.74539396,
       6.837785  ])

In [305]:
sorev = np.random.exponential(scale = 5, size=(10000,5))
X1 = np.min(sorev, axis=1)
Y1 = np.max(sorev, axis=1)
Z1 = Y1 - X1
p1 = Z1>5
sorev1 = sorev[sorev[:, 0] >3]
X2 = np.min(sorev1, axis=1)
Y2 = np.max(sorev1, axis=1)
Z2 = Y2 - X2
p2 = Z2>5
res = np.concatenate((X1, Y1[Y1 < 10]))
print(round(p1.mean(), 2), round(p2.mean(), 2), round(res.mean(), 2), sep='\n')

0.84
0.89
2.88


In [309]:
sorev[Y1 < 10]

array([[2.82121696, 2.20628305, 3.85797982, 0.1063728 , 0.98922751],
       [1.13103344, 7.77648425, 9.22663276, 2.85049416, 8.749719  ],
       [9.02502376, 5.69915083, 6.39965075, 4.73428617, 1.43211646],
       ...,
       [1.06841109, 0.23163795, 0.20843257, 6.46868747, 2.99936626],
       [2.2052219 , 3.77761001, 0.49566038, 0.76040231, 2.51840901],
       [4.71377444, 5.7637752 , 2.25045461, 4.69346547, 0.42054693]])

In [310]:
Y1 < 10

array([False,  True,  True, ..., False, False,  True])

In [311]:
sorev[1]

array([2.82121696, 2.20628305, 3.85797982, 0.1063728 , 0.98922751])

In [319]:
sorev = np.random.exponential(scale = 5, size=(10000,5))
X1 = np.min(sorev, axis=1)
Y1 = np.max(sorev, axis=1)
Z1 = Y1 - X1
p1 = Z1>5
sorev1 = sorev[sorev[:, 0] >3]
X2 = np.min(sorev1, axis=1)
Y2 = np.max(sorev1, axis=1)
Z2 = Y2 - X2
p2 = Z2>5
res = np.concatenate((X1, Y1[Y1 < 10]))
print(round(p1.mean(), 2), round(p2.mean(), 2), round(res.mean(), 2), sep='\n')

0.84
0.88
2.88
